### ISSUE TITLE
Feedback on SegmentationNetwork(pl.LightningModule) of module.py code #38

### ISSUE THREAD

**Issue by chenfh21** [PRBonn/phenobench-baselines#3]
https://github.com/PRBonn/phenobench-baselines/blob/78db625441e54c5b64efabeb0d886d020961665b/semantic_segmentation/modules/module.py#L38
Hello,
        Thanks a lot for providing all these baselines. I am really impressed by the structured repositories regarding the phenobench dataset.
        I just wanted to give some feedback on running the Semantic Segmentation baseline code.
        When calling torchmetrics when using JaccardIndex, it seems that the parameter "task" was omitted, and the torchmetrics version you provided is no longer supported.  I couldn't find the torchmetrics=0.8.1 version you specified.

**Comment by JaWeyl** [comment]
Hello Chenfh21,

Thanks for your feedback.
The signature of the `JaccardIndex` has changed quite a lot between different versions of *torchmetrics*.
You can find more details about this class at the specified version [here](https://torchmetrics.readthedocs.io/en/v0.8.1/classification/jaccard_index.html?highlight=jaccardindex).
