### ISSUE TITLE
About training configuration details

### ISSUE THREAD

**Issue by chenfh21** [PRBonn/phenobench-baselines#5]
Hi:
Thank you for providing all these baselines.
Now I am utilizing the baseline you provided and attempting to solve the relative issues. I have carefully read your article on Phenobench, which stated that you would provide details about training configuration in the supplement. Unfortunately， I did not find the supplement you mentioned. So I want to know if these details consistent with the parameters in the yaml file of the baseline.

**Comment by jbehley** [comment]
Short answer: yes, these are the configurations that we used for the results in the paper. Only the length of training (in terms of epochs or iteration) might be missing.

Long answer: The paper is currently under review and we felt that uploading a 100MB+ file with all the additional qualitative results to arxiv makes it "inconvenient" to download. The supplement will be available via our project page or the publisher website, once it's accepted. If you need the supplement now, I can provide you a link to download.

But we can also provide missing details via a github issue. Note that we also provide the checkpoints of the models and the predictions (on validation and testset) for full reproducibility.

**Comment by chenfh21** [comment]
Thanks for your response. 

If it's convenient, could you please provide the supplementary materials? It perhaps would be helpful for my research. I appreciate you sharing the download link. 







-----原始邮件-----
发件人:"Jens Behley" ***@***.***>
发送时间:2024-02-19 00:17:26 (星期一)
收件人: PRBonn/phenobench-baselines ***@***.***>
抄送: chenfh21 ***@***.***>, Author ***@***.***>
主题: Re: [PRBonn/phenobench-baselines] About training configuration detals (Issue #5)






Short answer: yes, these are the configurations that we used for the results in the paper. Only the length of training (in terms of epochs or iteration) might be missing.

Long answer: The paper is currently under review and we felt that uploading a 100MB+ file with all the additional qualitative results to arxiv makes it "inconvenient" to download. The supplement will be available via our project page or the publisher website, once it's accepted. If you need the supplement now, I can provide you a link to download.

But we can also provide missing details via a github issue. Note that we also provide the checkpoints of the models and the predictions (on validation and testset) for full reproducibility.

**Comment by jbehley** [comment]
Please find the draft of the supplement at https://www.phenobench.org/data/phenobench_supplement_draft.pdf

Hope that helps.
