### ISSUE TITLE
test set on CodaLab

### ISSUE THREAD

**Issue by chenfh21** [PRBonn/phenobench-baselines#7]
Hi,
I want to test my method on the test set, but the upload process on CodaLab seems too slow. My file exceeds your limit significantly, but it includes the method I proposed based on the baseline and the Phenobench dataset. 
The file format is semantic_baseline/my method 
                                                         /Phenobench_data/semantic/train&val&test(include an empty folder of 'semantics')
                                                         /description.txt

I don't know if this format is correct.

**Comment by JaWeyl** [comment]
Hi @chenfh21 ,

Please follow the instructions provided on CodLab to upload your results.

<img width="830" alt="codalab" src="https://github.com/user-attachments/assets/1c3243e8-0d4f-4f21-835d-5ee6fc2f66b1">


When you unzip the file you want to upload it should have the same structure as shown above.

**Comment by jbehley** [comment]
I think the issue has been resolved; therefore, I'm now closing it, but feel free to re-open it again if you still encounter problems.
