### ISSUE TITLE
Convert to Detectron2 Compatability 

### ISSUE THREAD

**Issue by jackmead515** [PRBonn/phenobench-baselines#8]
Took the liberty of converting the leaf instance segmentation model into a Detectron2 capable version. Hopefully is of some value to someone?

https://gist.github.com/jackmead515/802dfe49489b63927beb9f373ab494b0

**Comment by JaWeyl** [comment]
Hi @jackmead515 ,

Thank you for your efforts!
I'll close this issue - however, in case you see a need for further discussion just let me know.
